// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzDsMx7TvN7_S8Q0Y5SyyuhO2v_UlJDn4',
    appId: '1:1097750006446:web:24915721dcc614a1dd3b3f',
    messagingSenderId: '1097750006446',
    projectId: 'tafi-care',
    authDomain: 'tafi-care.firebaseapp.com',
    storageBucket: 'tafi-care.appspot.com',
    measurementId: 'G-PTY77QQMMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKJTeHH_NR5xa8MxH5ovQLPkA2P1prRuc',
    appId: '1:1097750006446:android:9c9702004eb345fadd3b3f',
    messagingSenderId: '1097750006446',
    projectId: 'tafi-care',
    storageBucket: 'tafi-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKBgG_ZBXQAU26plqQgLCd4eeO_6HtoZE',
    appId: '1:1097750006446:ios:2558e72ebc5c3fcadd3b3f',
    messagingSenderId: '1097750006446',
    projectId: 'tafi-care',
    storageBucket: 'tafi-care.appspot.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKBgG_ZBXQAU26plqQgLCd4eeO_6HtoZE',
    appId: '1:1097750006446:ios:e2296e5223b19249dd3b3f',
    messagingSenderId: '1097750006446',
    projectId: 'tafi-care',
    storageBucket: 'tafi-care.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzDsMx7TvN7_S8Q0Y5SyyuhO2v_UlJDn4',
    appId: '1:1097750006446:web:7a25eacd91665999dd3b3f',
    messagingSenderId: '1097750006446',
    projectId: 'tafi-care',
    authDomain: 'tafi-care.firebaseapp.com',
    storageBucket: 'tafi-care.appspot.com',
    measurementId: 'G-RSSW5J4P5J',
  );
}
