name: Build and Deploy Web

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  web:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter SDK
        uses: mobiledevops/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.22.2
      - run: flutter --version
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --release --base-href /tafi_care/
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/web
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
