on: [push]

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter SDK
        uses: mobiledevops/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.22.2 # Updated version
      - run: flutter --version
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

  second:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter SDK
        uses: mobiledevops/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.22.2 # Updated version
      - run: flutter --version
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter build apk --release
