# action.yml
# name: 'Flutter Mate'
# description: ' This action provides flutter for Github Actions.'
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   ---------------------------------------
# main.yml

name: Client build
on:
  push:
  
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  buildios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b v1.15.17 _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - uses: actions/checkout@v4
      - name: Install Flutter SDK
        uses: mobiledevops/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.4.3
      - run: flutter pub get
        working-directory: ./
      - run: flutter build ios --no-codesign
  buildandroid:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b v1.15.17 _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - name: Install Flutter SDK
        uses: mobiledevops/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.7.7
      - run: flutter pub get
        working-directory: ./
      - run: flutter build appbundle
