on: [push]

permissions:
  contents: write
  pages: write
  statuses: write
  id-token: write

jobs:
  # ios:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install Flutter SDK
  #       uses: mobiledevops/flutter-sdk-action@v1.0.0
  #       with:
  #         flutter-sdk-version: 3.22.2 # Updated version
  #     - run: flutter --version
  #     - run: flutter doctor
  #     - run: flutter pub get
  #     - run: flutter build ios --release --no-codesign
  #     - name: Upload build as artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: ios-app
  #         path: build/ios/iphoneos/Runner.app  

  # android:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install Flutter SDK
  #       uses: mobiledevops/flutter-sdk-action@v1.0.0
  #       with:
  #         flutter-sdk-version: 3.22.2 # Updated version
  #     - run: flutter --version
  #     - run: flutter doctor
  #     - run: flutter pub get
  #     #- run: flutter pub run flutter_launcher_icons:main # enable when need to change app icon
  #     - run: flutter build apk --release
  #     - name: Upload build as artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: android-app
  #         path: build/app/outputs/flutter-apk/app-release.apk  

  web:
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter SDK
        uses: mobiledevops/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.22.2 
      - run: flutter --version
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter build web --release
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload build as artifact
        uses: actions/upload-artifact@v3
        with:
          path:  build/web
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: test something
        run: ls build/web && mkdir public && cp -r build/web/* public/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
